import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Projeler bölümü, "projects/" klasöründeki dosyalardan otomatik olarak
 * oluşturulur. Yeni bir proje eklemek için o klasöre yeni bir .mdx dosyası
 * eklemeniz yeterli.
 */
const sidebars: SidebarsConfig = {
  projectsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
